### ISSUE TITLE
Avoid consent screen

### ISSUE THREAD

**Issue by sashasochka** [longlh/passport-google-oauth-jwt#1]
Hi,

Can you use this library with the following flow:
- Android app authenticates using Google SDK.
- app gets JWT token from Google.
- app sends the JWT token through REST to our node.js backend (without any consent screens)
- the user/app gets authenticated using passport-google-oauth-jwt

? 

If not, maybe you know any good suggestions for us.

Thanks,
Sasha.

**Comment by longlh** [comment]
Sorry for late response.

My library is intented to used only in server - server scenario (in-house project), so I did not test with client - server scenario.
